' https://plantuml.com/ja/sequence-diagram

@startuml sequence
skinparam sequenceMessageAlign center

actor       テスター            as tester
boundary    ブラウザ            as chrome
control     "クライアント側\nWebSocket Handler" as cWS
actor       管理者              as admin
participant server [
    =htmx-ws/broadcast.ts
    ----
    localhost:8080
]
control     "サーバー側\nWebSocket Handler" as sWS
control     "メッセージ・ルータ" as router
boundary    "他のブラウザ"       as others

== 管理者がサーバーを起動する ==
admin       ->   server     : bun ./broadcast.ts
activate server
server      ->   sWS        : create WebSocket Handler

== テスターがブラウザを開いてChat画面を呼び出す ==
tester      ->   chrome     : open browser
activate chrome
tester      ->   chrome     : localhost:8080
note over server: fetch(req, server) { ... }
chrome      ->   server     : HTTP Request GET /
chrome      <-   server     : HTTP Response チャット画面

== Htmx WS拡張がサーバー側WebSocketと接続する ==
chrome      ->   cWS        : HtmxのWS拡張を起動
activate cWS
cWS         ->   server     : HTTP Request GET /chat
server      ->   sWS        : server.upgrade(req)
deactivate server
note over sWS: websocket: open(ws) { ... }
cWS         <-   sWS        : ws.send("Welcome baby")
sWS         ->   router     : ws.subscribe(topic)
activate router
sWS         ->   router     : ws.publish(topic,"A new friend...")
cWS         <-   router     : <div hx-swap-oob="beforeend:#websocket_events"><li>A new friend...
router      ->   others     : 他のsubscribersにも\nメッセージを配達
deactivate router
chrome      <-   cWS        : DOMを書き換える
tester      <-   chrome     : 画面を更新して表示

== テスターが "Hello!" と入力してSubmitする ==
tester      ->   chrome     : Hello! と入力
tester      ->   chrome     : Submit
chrome      ->   cWS        : <form ws-send>
cWS         ->   sWS        : send JSON {"message":"Hello!"}
note over sWS: websocket: message(ws,data) { ... }
cWS         <-   sWS        : ws.send("Message from you: Hello!")
sWS         ->   router     : ws.publish(topic, message)
activate router
cWS         <-   router     : <div hx-swap-oob="beforeend:#websocket_events"><li>Hello!</li>
router      ->   others     : 他のsubscribersにも\nメッセージを配達
deactivate router
chrome      <-   cWS        : DOMを書き換える
tester      <-   chrome     : 画面を更新して表示

== サーバがメッセージを一方的に送信する ==
server      ->   server     : クライアントに依存しない任意の契機
note over sWS: websocket: message(ws,data) { ... }
server      ->   router     : server.publish("Hello from the Server")
activate router
cWS         <-   router     : <div hx-swap-oob="beforeend:#websocket_events"><li>Hello!</li>
router      ->   others     : 他のsubscribersにも\nメッセージを配達
deactivate router
chrome      <-   cWS        : DOMを書き換える
tester      <-   chrome     : 画面を更新して表示


'hnote over sws: topic:\nthe-group-chat
'note left: subscribe the topic 'the-group-chat'


@enduml
